/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     https://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
const fs = require('fs');

/**
 * returns string of html, with minor templating
 * TODO: switch to real template engine (pug?)
 */
function generateJS(params) {
   let downloadFrag = ""
   let titleFrag = `Fleet Debugger Historical: ${params.vehicle}`;
   if (params.live) {
      downloadFrag = `<a class="btn btn-primary" href='/vehicle.html' download>Click Here to Download</a>`;
      titleFrag = `Fleet Debugger Live: ${params.vehicle}`;
   }
   const template=`//File Generated By Dune Buggy
export class JSJSConfig {
   apikey = '${params.APIKEY}';
   jwt = '${params.jwt}';
   projectId = '${params.projectId}';
   tripId = '${params.tripId}';
}
   `;
   return template;
}

/**
 * Generates & writes html to specified file.  Existing file at location
 * will be overwritten.
 */
function writeJS(filePath, params) {
   const htmlStr = generateJS(params);
   fs.writeFileSync(filePath, htmlStr);
}

exports.writeJS = writeJS;
